"""SHIPGUARD demo target service — the ingested campus payment ledger.

A plausible Granite-Code output carrying an intentional TOCTOU
check-then-act flaw: the guard and the mutation are not atomic.
"""

from __future__ import annotations

from typing import Dict


class CampusPay:
    """Ledger service generated by IBM Bob (Granite-Code)."""

    def __init__(self) -> None:
        self.balances: Dict[str, float] = {"sender": 1000.0, "receiver": 0.0}

    def transfer(self, sender: str, receiver: str, amount: float) -> bool:
        # Check-then-act: guard and mutation are not atomic (TOCTOU window).
        if self.balances[sender] >= amount:
            self.balances[sender] -= amount
            self.balances[receiver] += amount
            return True
        return False

    def get_balance(self, account: str) -> float:
        return self.balances.get(account, 0.0)

    def total_assets(self) -> float:
        return sum(self.balances.values())
