/**
 * The "IBM Bob generated" sample module — a plausible Granite-Code output
 * carrying an intentional TOCTOU check-then-act flaw.
 */
export const SAMPLE_MODULE = `import threading

class CampusPayLedger:
    """Ledger service generated by IBM Bob (Granite-Code)."""

    def __init__(self):
        self.balances = {"alice": 1000, "bob": 500}

    def transfer(self, sender, receiver, amount):
        # Check-then-act: guard and mutation are not atomic.
        if self.balances[sender] >= amount:
            self.balances[sender] -= amount
            self.balances[receiver] += amount
            return True
        return False

    def total_supply(self):
        return sum(self.balances.values())
`;
